from rf import *

#runs all the functions.
a = 10
b = 120

print(add(a, b))
print(add_literal(a, b))
print(diff(a, b))
print(div1(a, b))
print(min1(a, b))
print(fiftytwothousandonehundredthirtyseven(a, b))
print(candiv(a, b))
print(reverse(a, b))
print(digsort(a, b))
print(interlace(a, b))
print("---")

print(multiply3(a, b))
print(mod(a, b))
print(squaresum(a, b))
print(lin10(a, b))
print(gcd(a, b))
print(roundb(a, b))
print(div2(a, b))
print(digcounts(a, b))
print(gozinta(a, b))
print(evensum(a, b))
print(digsum(a, b))
print("---")

print(divdig(a, b))
print(rand1(a, b))
print(hyp(a, b))
print(digcount(a, b))
print(digpairsum(a, b))
print(digsumnum(a, b))
print(dist(a, b))
print(fibonacci(a, b))
print(collatz(a, b))
print(sumvardig(a, b))
print("---")

print(cubehole(a, b))
print(cylinder(a, b))
print(angle(a, b))
print(pidig(a, b))
print(ball(a, b))
print(coinflip(a, b))
print(rectnum(a, b))
print(custom1(a, b))
print(custom2(a, b))
print(custom3(a, b))
print("---")

print(sumround(a, b))
print(reimann(a, b))
print(acceldist(a, b))
print(baseconv(a, b))
print(multtablesum(a, b))
print(binarytablesum(a, b))
print(mult5(a, b))
print(addtablesum(a, b))
print(geoarithseries(a, b))
print(seriesproduct(a, b))


